[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1000000
via_ir = true
evm_version = "cancun"
fs_permissions = [
    { access = "read-write", path = "./web" },
    { access = "read-write", path = "./deployments.json" }
]

[profile.default.fuzz]
runs = 10000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"
